#!/bin/bash
# bible-cc-plugin complete uninstall — stops daemon, removes ALL local state.
# Usage: ./scripts/uninstall.sh [--force]
#
# SAFETY: This script targets ~/.bible-cc/ and standard plugin install paths
# only. It NEVER deletes the current working directory. The plugin directory is
# only removed when it matches a known install location AND contains plugin.json.
set -euo pipefail

FORCE="${1:-}"
DAEMON_FLAGS=""
if [ "$FORCE" = "--force" ]; then
    DAEMON_FLAGS="--force"
fi

# ── Confirmation (skip with --force) ─────────────────────
if [ "$FORCE" != "--force" ]; then
    echo "This will:"
    echo "  1. Stop the bible-cc daemon"
    echo "  2. Delete ~/.bible-cc/ (all config + data)"
    echo "  3. Delete ~/.claude/plugins/bible-cc-plugin/ (plugin)"
    echo "  4. Remove generated .mcp.json"
    echo "  5. Clean up settings.json plugin registration"
    echo ""
    read -rp "Continue? [y/N] " CONFIRM
    case "$CONFIRM" in
        [yY]|[yY][eE][sS]) ;;
        *) echo "Aborted."; exit 0 ;;
    esac
fi

echo "==> Stopping daemon..."
cd "$(dirname "$0")/.."
uv run python scripts/daemon.py stop $DAEMON_FLAGS 2>/dev/null || true

echo "==> Removing ~/.bible-cc/ (config + data)..."
rm -rf ~/.bible-cc/

# ── Plugin directory removal ──────────────────────────────
# Only remove from STANDARD install locations — NEVER use pwd.
# If the plugin was cloned elsewhere, the user must remove it manually.
STANDARD_PATHS=(
    "$HOME/.claude/plugins/bible-cc-plugin"
    "$HOME/.claude-plugins/bible-cc-plugin"
)
REMOVED=0
for PLUGIN_DIR in "${STANDARD_PATHS[@]}"; do
    if [ -d "$PLUGIN_DIR" ]; then
        # Safety check: directory must contain plugin.json to confirm it's us
        if [ -f "$PLUGIN_DIR/.claude-plugin/plugin.json" ]; then
            echo "==> Removing plugin directory: $PLUGIN_DIR"
            cd ~
            rm -rf "$PLUGIN_DIR"
            REMOVED=1
        else
            echo "!! Skipping $PLUGIN_DIR (exists but missing plugin.json — not a bible-cc install)"
        fi
    fi
done

if [ $REMOVED -eq 0 ]; then
    echo "==> No standard plugin directory found to remove."
    echo "    If installed elsewhere, remove manually."
fi

# ── Clean up generated files in workspace ─────────────────
# .mcp.json is generated by setup.py, not committed. Remove it so Claude Code
# won't discover a stale MCP server definition in this directory.
if [ -f .mcp.json ]; then
    rm -f .mcp.json
    echo "==> Removed .mcp.json (generated MCP config)"
fi

# ── Clean up Claude Code plugin registration ─────────────
if [ -f "$HOME/.claude/settings.json" ]; then
    python3 -c "
import json, os
path = os.path.expanduser('~/.claude/settings.json')
cfg = json.load(open(path))
if 'bible-cc-plugin@skills-dir' in cfg.get('enabledPlugins', {}):
    del cfg['enabledPlugins']['bible-cc-plugin@skills-dir']
    json.dump(cfg, open(path, 'w'), indent=4)
    print('Removed bible-cc-plugin from settings.json enabledPlugins')
"
fi

echo "==> Uninstall complete."
echo "To reinstall: git clone <repo-url> ~/.claude/plugins/bible-cc-plugin && cd ~/.claude/plugins/bible-cc-plugin && uv sync"
